// <auto-generated />
using Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20240229194847_UpdateVarietalSeeder")]
    partial class UpdateVarietalSeeder
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Api.Models.Crop", b =>
                {
                    b.Property<int>("CropId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("CropId");

                    b.ToTable("Crops");

                    b.HasData(
                        new
                        {
                            CropId = 1,
                            Name = "Tomato"
                        },
                        new
                        {
                            CropId = 2,
                            Name = "Grape"
                        },
                        new
                        {
                            CropId = 3,
                            Name = "Pear"
                        },
                        new
                        {
                            CropId = 4,
                            Name = "Blackberry"
                        });
                });

            modelBuilder.Entity("Api.Models.Varietal", b =>
                {
                    b.Property<int>("VarietalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CropId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("VarietalId");

                    b.HasIndex("CropId");

                    b.ToTable("Varietals");

                    b.HasData(
                        new
                        {
                            VarietalId = 1,
                            CropId = 1,
                            Description = "Small, sweet tomato variety.",
                            Name = "Cherry Tomato"
                        },
                        new
                        {
                            VarietalId = 2,
                            CropId = 1,
                            Description = "Meatier, less juicy tomato variety.",
                            Name = "Roma Tomato"
                        },
                        new
                        {
                            VarietalId = 3,
                            CropId = 2,
                            Description = "Red wine grape variety.",
                            Name = "Cabernet Sauvignon"
                        },
                        new
                        {
                            VarietalId = 4,
                            CropId = 2,
                            Description = "White wine grape variety.",
                            Name = "Chardonnay"
                        },
                        new
                        {
                            VarietalId = 5,
                            CropId = 3,
                            Description = "Not sure how to describe this.",
                            Name = "Asian"
                        });
                });

            modelBuilder.Entity("Api.Models.Varietal", b =>
                {
                    b.HasOne("Api.Models.Crop", "Crop")
                        .WithMany("Varietals")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crop");
                });

            modelBuilder.Entity("Api.Models.Crop", b =>
                {
                    b.Navigation("Varietals");
                });
#pragma warning restore 612, 618
        }
    }
}
