// <auto-generated />
using Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20240224062623_UpdateCropWithType")]
    partial class UpdateCropWithType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Api.Models.Crop", b =>
                {
                    b.Property<int>("CropId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("CropId");

                    b.ToTable("Crops");

                    b.HasData(
                        new
                        {
                            CropId = 1,
                            Name = "Tomato"
                        },
                        new
                        {
                            CropId = 2,
                            Name = "Grape"
                        },
                        new
                        {
                            CropId = 3,
                            Name = "Pear"
                        },
                        new
                        {
                            CropId = 4,
                            Name = "Blackberry"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
